#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(
        KC_1,        KC_2,        KC_3,        KC_4,        KC_5,        KC_6,            KC_NO,       KC_NO,       KC_7,        KC_8,        KC_9,        KC_0,        KC_GRV,       KC_NO,
        KC_TAB,      KC_V,        KC_W,        KC_G,        KC_M,        KC_J,            KC_NO,       KC_NO,       KC_SCLN,     KC_DOT,      KC_QUOT,     KC_EQL,      KC_SLSH,      KC_BSLS,
        LGUI_T(KC_S),LALT_T(KC_N),LCTL_T(KC_T),LSFT_T(KC_H),KC_K,        KC_NO,           KC_NO,       KC_COMM,     RSFT_T(KC_A),RCTL_T(KC_E),RALT_T(KC_I),RGUI_T(KC_C),KC_NO,        KC_NO,
        KC_F,        KC_P,        KC_D,        KC_L,        KC_X,        KC_ESC,          KC_NO,       KC_NO,       KC_DEL,      KC_MINS,     KC_U,        KC_O,        KC_Y,         KC_B,
                                          MO(1),        KC_LALT,     KC_R,            KC_ENT,      KC_TAB,      KC_SPC,      KC_BSPC,     KC_NO,       KC_NO
    ),
    [1] = LAYOUT(
        KC_F1,      KC_F2,      KC_F3,      KC_F4,      KC_F5,      KC_F6,        KC_NO,       KC_NO,       KC_F7,      KC_F8,      KC_F9,      KC_F10,      KC_F11,      KC_F12,
        KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,        KC_NO,       KC_NO,       KC_LCBR,    KC_RCBR,    KC_MINS,    KC_EQL,      KC_HOME,     KC_PGUP,
        KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,        KC_NO,       KC_NO,       KC_LEFT,    KC_UP,      KC_DOWN,    KC_RGHT,     KC_END,      KC_PGDN,
        KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,        KC_NO,       KC_NO,       KC_NO,      KC_NO,      KC_NO,      KC_NO,       KC_NO,      KC_NO,
                                          DF(5),      KC_NO,       KC_NO,        KC_LBRC,    KC_RBRC,    KC_NO,       KC_NO,      KC_NO,      KC_NO
    ),
    [2] = LAYOUT(
        KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,        KC_NO,       KC_NO,       KC_NO,      KC_NO,      KC_NO,      KC_NO,       KC_NO,      KC_NO,
        KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,        KC_NO,       KC_NO,       KC_NO,      KC_NO,      KC_NO,      KC_NO,       KC_NO,      KC_NO,
        KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,        KC_NO,       KC_NO,       KC_NO,      KC_NO,      KC_NO,      KC_NO,       KC_NO,      KC_NO,
        KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,        KC_NO,       KC_NO,       KC_NO,      KC_NO,      KC_NO,      KC_NO,       KC_NO,      KC_NO,
                                          KC_NO,      KC_NO,       KC_NO,        KC_NO,      KC_NO,      KC_NO,       KC_NO,      KC_NO,      KC_NO
    ),
    [3] = LAYOUT(
        KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,        KC_NO,       KC_NO,       KC_NO,      KC_NO,      KC_NO,      KC_NO,       KC_NO,      KC_NO,
        KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,        KC_NO,       KC_NO,       KC_NO,      KC_NO,      KC_NO,      KC_NO,       KC_NO,      KC_NO,
        KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,        KC_NO,       KC_NO,       KC_NO,      KC_NO,      KC_NO,      KC_NO,       KC_NO,      KC_NO,
        KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,        KC_NO,       KC_NO,       KC_NO,      KC_NO,      KC_NO,      KC_NO,       KC_NO,      KC_NO,
                                          KC_NO,      KC_NO,       KC_NO,        KC_NO,      KC_NO,      KC_NO,       KC_NO,      KC_NO,      KC_NO
    ),
    [4] = LAYOUT(
        KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,        KC_NO,       KC_NO,       KC_NO,      KC_NO,      KC_NO,      KC_NO,       KC_NO,      KC_NO,
        KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,        KC_NO,       KC_NO,       KC_NO,      KC_NO,      KC_NO,      KC_NO,       KC_NO,      KC_NO,
        KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,        KC_NO,       KC_NO,       KC_NO,      KC_NO,      KC_NO,      KC_NO,       KC_NO,      KC_NO,
        KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,        KC_NO,       KC_NO,       KC_NO,      KC_NO,      KC_NO,      KC_NO,       KC_NO,      KC_NO,
                                          KC_NO,      KC_NO,       KC_NO,        KC_NO,      KC_NO,      KC_NO,       KC_NO,      KC_NO,      KC_NO
    ),
    [5] = LAYOUT(
        KC_1,        KC_2,        KC_3,        KC_4,        KC_5,        KC_6,            KC_NO,       KC_NO,       KC_7,        KC_8,        KC_9,        KC_0,        KC_GRV,       KC_BSPC,
        KC_TAB,      KC_Q,        KC_W,        KC_E,        KC_R,        KC_T,            KC_NO,       KC_NO,       KC_Y,        KC_U,        KC_I,        KC_O,        KC_P,         KC_BSLS,
        KC_LCTL,     KC_A,        KC_S,        KC_D,        KC_F,        KC_G,            KC_NO,       KC_NO,       KC_H,        KC_J,        KC_K,        KC_L,        KC_SCLN,     KC_QUOT,
        KC_LSFT,     KC_Z,        KC_X,        KC_C,        KC_V,        KC_B,            KC_ESC,      KC_NO,       KC_DEL,      KC_N,        KC_M,        KC_COMM,     KC_DOT,      KC_SLSH,
                                          KC_RSFT,     MO(6),       KC_NO,           KC_SPC,      KC_ENT,      KC_ENT,      KC_SPC,      KC_NO,       KC_NO
    ),
    [6] = LAYOUT(
        KC_F1,      KC_F2,      KC_F3,      KC_F4,      KC_F5,      KC_F6,        KC_NO,       KC_NO,       KC_F7,      KC_F8,      KC_F9,      KC_F10,      KC_F11,      KC_F12,
        KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,        KC_NO,       KC_NO,       KC_LCBR,    KC_RCBR,    KC_MINS,    KC_EQL,      KC_HOME,     KC_PGUP,
        KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,        KC_NO,       KC_NO,       KC_LEFT,    KC_UP,      KC_DOWN,    KC_RGHT,     KC_END,      KC_PGDN,
        KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,        KC_NO,       KC_NO,       KC_NO,      KC_NO,      KC_NO,      KC_NO,       KC_NO,      KC_NO,
                                          DF(0),      KC_NO,       KC_NO,        KC_LBRC,    KC_RBRC,    KC_NO,       KC_NO,      KC_NO,      KC_NO
    )
};
